kind: BuildConfig
apiVersion: v1
metadata:
  name: whirlwind-caravan-build
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/sparkhara/whirlwind-caravan"
      ref: "master"
  strategy:
    type: "Docker"
  output:
    to:
      kind: "ImageStreamTag"
      name: "whirlwind-caravan:latest"
